### ISSUE TITLE
robot.speak continues from old controller to new controller

### ISSUE THREAD

**Issue by lmeeden1** [Calysto/jyrobot#12]
If you have multiple controllers in the same notebook, if the previous one was speaking, then the next one will continue to say the last message.  Should reset the speak message at the start of every control session.

**Comment by dsblank** [comment]
Yeah, good point. I guess start run, seconds, or steps should start out with a blank slate.

**Comment by dsblank** [comment]
Fixed (maybe) with 4a8df6961077cd9ce8dd75b6dea6553759f5937e

This change resets the pen, speech bubble, and trace trail when the robot's pose is set. That way, you can continue as it is, but a reset should clear it. You can also clear it manually with `robot.speak()`
