### ISSUE TITLE
world.watch() doesn't show robot until world.reset() is done

### ISSUE THREAD

**Issue by lmeeden1** [Calysto/jyrobot#6]
Whenever I try to watch a world, the robot doesn't show up until I do world.resetI().  Here's an example world definition:

# Create a world with one wall and a robot

world = jyrobot.World(width=200, height=200)
world.add_wall("blue", 80, 50, 100, 150)
robot = jyrobot.Scribbler(x=50, y=100, direction=0)
robot.add_device(jyrobot.RangeSensor(position=(6,-6),width=57.3,max=20,angle=90,name="left-ir"))
robot.add_device(jyrobot.RangeSensor(position=(6,6),width=57.3,max=20,angle=90,name="right=ir"))
world.add_robot(robot)
world.update()
world.save()

**Comment by dsblank** [comment]
Fixed in 232ef45

Also, scaled the world up a bit in your example to increase resolution and make it look a bit better:

![Screenshot from 2021-01-22 10-29-09](https://user-images.githubusercontent.com/168568/105530553-ce41bb80-5c9c-11eb-9dab-4c83edc793ac.png)
